# Generated by Django 2.2.3 on 2019-07-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0003_userconnection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'user')},
        ),
    ]
